In [1]:
import numpy as np

In [2]:
#1a
arr = np.random.rand(3,3)

print(arr,"\n")
print(np.mean(arr, axis=1),"\n")
print(np.std(arr, axis=1),"\n")
print(np.var(arr, axis=1),"\n")

[[0.82515312 0.96120158 0.25962798]
 [0.74118048 0.17515633 0.69247193]
 [0.43428156 0.03180366 0.3703556 ]] 

[0.68199423 0.53626958 0.27881361] 

[0.30377868 0.25611874 0.17660137] 

[0.09228149 0.06559681 0.03118804] 



In [3]:
#1b
m, n = map(int, input("Enter the size: ").split())
arr = np.random.randint(1,10,(m,n))
print(arr)

print(arr.shape)
print(type(arr))
print(arr.dtype)

arr2 = arr.reshape(n,m)
print(arr2)

[[6 5 3 3]
 [5 6 3 8]
 [2 7 7 5]]
(3, 4)
<class 'numpy.ndarray'>
int64
[[6 5 3]
 [3 5 6]
 [3 8 2]
 [7 7 5]]


In [4]:
arr1d = np.array([0,1,np.nan,5,0])

print(np.where(arr1d==0)[0])
print(np.where(np.isnan(arr1d))[0])
print(np.where((arr1d!=0) & ~np.isnan(arr1d))[0])

[0 4]
[2]
[1 3]


In [5]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
arr3 = np.random.randint(1,10,5)

print(arr1,"\n",arr2,"\n",arr3)

arr4 = np.subtract(arr3,arr2)
print(arr4)

arr5 = np.multiply(arr1,2)
print(arr5)

print("\n")
print(np.cov(arr1,arr4))
print(np.corrcoef(arr1,arr5))

[4 2 1 3 8] 
 [5 6 4 9 9] 
 [2 2 3 2 3]
[-3 -4 -1 -7 -6]
[ 8  4  2  6 16]


[[ 7.3 -3.6]
 [-3.6  5.7]]
[[1. 1.]
 [1. 1.]]


In [6]:
A1 = np.random.randint(1,10,10)
A2 = np.random.randint(1,10,10)

sum_arr = np.sum(A1[:5] + A2[:5])
mult_arr = np.prod(A1[5:]*A2[5:])

print("\n",sum_arr,"\n",mult_arr)


 59 
 403200


In [7]:
arr_mem = np.random.rand(10,10)
print(arr_mem.nbytes)

800


In [8]:
arr_g = np.random.randint(10,100,(3,4))
print(arr_g)

arr_g[[0,1]] = arr_g[[1,0]]
print(arr_g)

arr_g2 = arr_g.copy()
arr_g2[:,1] = arr_g2[::-1,1]
print(arr_g2)

[[36 87 87 19]
 [75 59 31 87]
 [78 14 61 85]]
[[75 59 31 87]
 [36 87 87 19]
 [78 14 61 85]]
[[75 14 31 87]
 [36 87 87 19]
 [78 59 61 85]]


In [9]:
#2a
import pandas as pd

s = pd.Series([5,2,9,1,7], index=['e','b','a','d','c'])
print(s)

print(s.sort_index())
print(s.sort_values())

e    5
b    2
a    9
d    1
c    7
dtype: int64
a    9
b    2
c    7
d    1
e    5
dtype: int64
d    1
b    2
e    5
c    7
a    9
dtype: int64


In [10]:
#b
s2 = pd.Series([10,20,30,20,20,10])
print(s2)
print(s2.rank(method='first'))
print(s2.rank(method='max'))

0    10
1    20
2    30
3    20
4    20
5    10
dtype: int64
0    1.0
1    3.0
2    6.0
3    4.0
4    5.0
5    2.0
dtype: float64
0    2.0
1    5.0
2    6.0
3    5.0
4    5.0
5    2.0
dtype: float64


In [11]:
#c
print(s.idxmax())
print(s.idxmin())

a
d


In [28]:
#3a 
df = pd.DataFrame(np.random.randn(50,3),columns=['A','B','C'])
for _ in range(int(0.1*df.size)):
    i = np.random.randint(0,50)
    j = np.random.randint(0,3)
    df.iat[i,j] = np.nan

print(df)

           A         B         C
0   0.008315 -0.341430  0.790271
1   0.277635 -2.354425  0.034806
2  -1.134259 -0.396760  2.093176
3   1.463534 -0.384614  1.152495
4   0.703059  1.132424 -0.193098
5   0.547265  0.376094 -0.681380
6  -0.159177 -0.563010 -0.899438
7   0.128965  0.595763  0.966258
8   0.036600  0.704322 -0.524841
9   0.471018  2.071556  0.053311
10 -1.262271  1.105158 -0.185655
11  0.004540 -1.803752 -0.126550
12  0.333697 -0.858673  0.754760
13 -0.964541  0.317334 -2.224753
14 -0.093676       NaN       NaN
15  0.331953  0.841252  1.310020
16 -1.904518 -0.627974 -0.127048
17  0.512573  0.310445 -0.347367
18  0.453252  0.277887       NaN
19 -2.495970  0.552770 -1.308226
20 -0.109512 -0.332256 -0.055441
21 -1.041520 -0.992900       NaN
22  0.796317  0.206774       NaN
23 -1.892902  1.093577 -0.790744
24       NaN  1.669615       NaN
25 -0.135257 -1.239878  0.860452
26       NaN  0.653576  0.401613
27 -0.451368       NaN -0.346452
28  0.215449 -1.696670  0.859706
29 -0.9721

In [29]:
print("Missing Values:\n",df.isnull().sum())

df = df.dropna(axis = 1, thresh=45)
print(df)

Missing Values:
 A    3
B    5
C    6
dtype: int64
           A         B
0   0.008315 -0.341430
1   0.277635 -2.354425
2  -1.134259 -0.396760
3   1.463534 -0.384614
4   0.703059  1.132424
5   0.547265  0.376094
6  -0.159177 -0.563010
7   0.128965  0.595763
8   0.036600  0.704322
9   0.471018  2.071556
10 -1.262271  1.105158
11  0.004540 -1.803752
12  0.333697 -0.858673
13 -0.964541  0.317334
14 -0.093676       NaN
15  0.331953  0.841252
16 -1.904518 -0.627974
17  0.512573  0.310445
18  0.453252  0.277887
19 -2.495970  0.552770
20 -0.109512 -0.332256
21 -1.041520 -0.992900
22  0.796317  0.206774
23 -1.892902  1.093577
24       NaN  1.669615
25 -0.135257 -1.239878
26       NaN  0.653576
27 -0.451368       NaN
28  0.215449 -1.696670
29 -0.972113 -2.007142
30 -1.457661 -0.629572
31 -0.895821 -0.960989
32 -1.585029 -0.571151
33 -1.225788 -0.528192
34  0.003139 -0.441887
35  2.410730 -1.135738
36 -0.095511  0.276855
37  0.056312 -1.029105
38 -0.850204       NaN
39  0.782777       NaN
40 -1.

In [30]:
if df.shape[1] > 0:
    idmax = df.sum(axis=1).idxmax()
    df = df.drop(idmax)

print(df)

           A         B
0   0.008315 -0.341430
1   0.277635 -2.354425
2  -1.134259 -0.396760
3   1.463534 -0.384614
4   0.703059  1.132424
5   0.547265  0.376094
6  -0.159177 -0.563010
7   0.128965  0.595763
8   0.036600  0.704322
9   0.471018  2.071556
10 -1.262271  1.105158
11  0.004540 -1.803752
12  0.333697 -0.858673
13 -0.964541  0.317334
14 -0.093676       NaN
15  0.331953  0.841252
16 -1.904518 -0.627974
17  0.512573  0.310445
18  0.453252  0.277887
19 -2.495970  0.552770
20 -0.109512 -0.332256
21 -1.041520 -0.992900
22  0.796317  0.206774
23 -1.892902  1.093577
24       NaN  1.669615
25 -0.135257 -1.239878
26       NaN  0.653576
27 -0.451368       NaN
28  0.215449 -1.696670
29 -0.972113 -2.007142
30 -1.457661 -0.629572
31 -0.895821 -0.960989
32 -1.585029 -0.571151
33 -1.225788 -0.528192
34  0.003139 -0.441887
35  2.410730 -1.135738
36 -0.095511  0.276855
37  0.056312 -1.029105
38 -0.850204       NaN
39  0.782777       NaN
40 -1.786377       NaN
41  2.180735 -1.205326
42 -0.17699

In [32]:
if "A" in df.columns:
    df = df.sort_values(by='A')
    df = df.drop_duplicates(subset='A')

if 'A' in df.columns and 'B' in df.columns:
    print(df['A'].corr(df['B']))


if 'B' in df.columns:
    df['B_bins'] = pd.cut(df['B'], bins=5)
    print(df.head())

-0.07476867277591694
           A         B            B_bins
19 -2.495970  0.552770    (0.301, 1.186]
16 -1.904518 -0.627974  (-1.469, -0.584]
23 -1.892902  1.093577    (0.301, 1.186]
40 -1.786377       NaN               NaN
32 -1.585029 -0.571151   (-0.584, 0.301]
