In [1]:
import numpy as np

In [2]:
#1a
arr = np.random.rand(3,3)

print(arr,"\n")
print(np.mean(arr, axis=1),"\n")
print(np.std(arr, axis=1),"\n")
print(np.var(arr, axis=1),"\n")

[[0.03372247 0.32478584 0.06524567]
 [0.99583739 0.59141675 0.34270457]
 [0.30269218 0.63827071 0.7164569 ]] 

[0.14125133 0.64331957 0.55247326] 

[0.13041502 0.26915429 0.17948298] 

[0.01700808 0.07244403 0.03221414] 



In [3]:
#1b
m, n = map(int, input("Enter the size: ").split())
arr = np.random.randint(1,10,(m,n))
print(arr)

print(arr.shape)
print(type(arr))
print(arr.dtype)

arr2 = arr.reshape(n,m)
print(arr2)

[[1 7 8 6]
 [3 7 1 3]
 [5 6 5 1]]
(3, 4)
<class 'numpy.ndarray'>
int64
[[1 7 8]
 [6 3 7]
 [1 3 5]
 [6 5 1]]


In [4]:
arr1d = np.array([0,1,np.nan,5,0])

print(np.where(arr1d==0)[0])
print(np.where(np.isnan(arr1d))[0])
print(np.where((arr1d!=0) & ~np.isnan(arr1d))[0])

[0 4]
[2]
[1 3]


In [5]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
arr3 = np.random.randint(1,10,5)

print(arr1,"\n",arr2,"\n",arr3)

arr4 = np.subtract(arr3,arr2)
print(arr4)

arr5 = np.multiply(arr1,2)
print(arr5)

print("\n")
print(np.cov(arr1,arr4))
print(np.corrcoef(arr1,arr5))

[4 7 7 3 5] 
 [7 2 6 9 9] 
 [6 2 1 6 6]
[-1  0 -5 -3 -3]
[ 8 14 14  6 10]


[[ 3.2  -0.15]
 [-0.15  3.8 ]]
[[1. 1.]
 [1. 1.]]


In [6]:
A1 = np.random.randint(1,10,10)
A2 = np.random.randint(1,10,10)

sum_arr = np.sum(A1[:5] + A2[:5])
mult_arr = np.prod(A1[5:]*A2[5:])

print("\n",sum_arr,"\n",mult_arr)


 61 
 7464960


In [7]:
arr_mem = np.random.rand(10,10)
print(arr_mem.nbytes)

800


In [8]:
arr_g = np.random.randint(10,100,(3,4))
print(arr_g)

arr_g[[0,1]] = arr_g[[1,0]]
print(arr_g)

arr_g2 = arr_g.copy()
arr_g2[:,1] = arr_g2[::-1,1]
print(arr_g2)

[[63 23 62 92]
 [20 55 44 16]
 [34 18 36 57]]
[[20 55 44 16]
 [63 23 62 92]
 [34 18 36 57]]
[[20 18 44 16]
 [63 23 62 92]
 [34 55 36 57]]


In [9]:
#2a
import pandas as pd

s = pd.Series([5,2,9,1,7], index=['e','b','a','d','c'])
print(s)

print(s.sort_index())
print(s.sort_values())

e    5
b    2
a    9
d    1
c    7
dtype: int64
a    9
b    2
c    7
d    1
e    5
dtype: int64
d    1
b    2
e    5
c    7
a    9
dtype: int64


In [10]:
#b
s2 = pd.Series([10,20,30,20,20,10])
print(s2)
print(s2.rank(method='first'))
print(s2.rank(method='max'))

0    10
1    20
2    30
3    20
4    20
5    10
dtype: int64
0    1.0
1    3.0
2    6.0
3    4.0
4    5.0
5    2.0
dtype: float64
0    2.0
1    5.0
2    6.0
3    5.0
4    5.0
5    2.0
dtype: float64


In [11]:
#c
print(s.idxmax())
print(s.idxmin())

a
d


In [12]:
#3a 
df = pd.DataFrame(np.random.randn(50,3),columns=['A','B','C'])
for _ in range(int(0.1*df.size)):
    i = np.random.randint(0,50)
    j = np.random.randint(0,3)
    df.iat[i,j] = np.nan

print(df)

           A         B         C
0   0.894906  1.176606 -0.828301
1  -0.002783 -0.020856  1.168649
2   0.716014  0.706116 -1.997647
3   0.342974 -0.846518  0.616150
4  -1.369429 -0.845237       NaN
5  -0.589753       NaN -0.617299
6  -0.080576  1.550934  0.687990
7   0.845270  0.815464  2.149891
8  -2.154295  1.161687 -0.714444
9  -0.133932 -0.879301 -0.724851
10 -0.877878  0.740433 -0.833393
11 -0.821978 -1.263162  0.081407
12       NaN -0.516534 -0.744417
13  0.298854 -0.456649  0.165167
14 -1.451342  0.718761       NaN
15 -1.569379  0.195038 -0.900615
16       NaN  0.560806  0.984667
17 -0.976734  0.035715  0.603267
18       NaN -0.110053       NaN
19 -0.461258 -0.388120       NaN
20 -1.441898  0.689383 -2.185597
21  0.240779       NaN -0.544757
22  0.643898  0.899636  0.114619
23  0.048272 -0.930872 -3.144997
24  1.573758 -0.750740  0.179598
25  0.560490  0.268712  1.348868
26  0.110490 -1.215037  1.988783
27 -0.853895  0.267457  0.642918
28  0.511576 -0.164674  0.078997
29  1.1450

In [13]:
print("Missing Values:\n",df.isnull().sum())

df = df.dropna(axis = 1, thresh=45)
print(df)

Missing Values:
 A    4
B    6
C    4
dtype: int64
           A         C
0   0.894906 -0.828301
1  -0.002783  1.168649
2   0.716014 -1.997647
3   0.342974  0.616150
4  -1.369429       NaN
5  -0.589753 -0.617299
6  -0.080576  0.687990
7   0.845270  2.149891
8  -2.154295 -0.714444
9  -0.133932 -0.724851
10 -0.877878 -0.833393
11 -0.821978  0.081407
12       NaN -0.744417
13  0.298854  0.165167
14 -1.451342       NaN
15 -1.569379 -0.900615
16       NaN  0.984667
17 -0.976734  0.603267
18       NaN       NaN
19 -0.461258       NaN
20 -1.441898 -2.185597
21  0.240779 -0.544757
22  0.643898  0.114619
23  0.048272 -3.144997
24  1.573758  0.179598
25  0.560490  1.348868
26  0.110490  1.988783
27 -0.853895  0.642918
28  0.511576  0.078997
29  1.145016  0.498407
30 -1.367510 -0.312076
31  0.831167  0.055902
32 -0.660526 -0.540965
33 -1.793181 -0.105658
34 -0.123788 -1.883280
35  0.614751 -1.519162
36 -1.349675  0.711582
37  3.093984  1.804372
38  0.762160  0.109187
39  0.231469 -1.524196
40 -0.

In [14]:
if df.shape[1] > 0:
    idmax = df.sum(axis=1).idxmax()
    df = df.drop(idmax)

print(df)

           A         C
0   0.894906 -0.828301
1  -0.002783  1.168649
2   0.716014 -1.997647
3   0.342974  0.616150
4  -1.369429       NaN
5  -0.589753 -0.617299
6  -0.080576  0.687990
7   0.845270  2.149891
8  -2.154295 -0.714444
9  -0.133932 -0.724851
10 -0.877878 -0.833393
11 -0.821978  0.081407
12       NaN -0.744417
13  0.298854  0.165167
14 -1.451342       NaN
15 -1.569379 -0.900615
16       NaN  0.984667
17 -0.976734  0.603267
18       NaN       NaN
19 -0.461258       NaN
20 -1.441898 -2.185597
21  0.240779 -0.544757
22  0.643898  0.114619
23  0.048272 -3.144997
24  1.573758  0.179598
25  0.560490  1.348868
26  0.110490  1.988783
27 -0.853895  0.642918
28  0.511576  0.078997
29  1.145016  0.498407
30 -1.367510 -0.312076
31  0.831167  0.055902
32 -0.660526 -0.540965
33 -1.793181 -0.105658
34 -0.123788 -1.883280
35  0.614751 -1.519162
36 -1.349675  0.711582
38  0.762160  0.109187
39  0.231469 -1.524196
40 -0.561005 -1.129617
41       NaN -0.095394
42  0.163875  0.902126
43 -0.98527

In [15]:
if "A" in df.columns:
    df = df.sort_values(by='A')
    df = df.drop_duplicates(subset='A')

if 'A' in df.columns and 'B' in df.columns:
    print(df['A'].corr(df['B']))


if 'B' in df.columns:
    df['B_bins'] = pd.cut(df['B'], bins=5)
    print(df.head())

In [19]:
df1 = pd.read_excel("file1.xlsx")
df2 = pd.read_excel("file2.xlsx")

print(pd.merge(df1,df2, on="Name"))

   Name     Date_x  duration_x     Date_y  duration_y
0     B 2023-01-02          50 2023-01-01          40
1     B 2023-01-02          50 2023-01-03          40
2     B 2023-01-02          50 2023-01-02          30
3     B 2023-01-02          50 2023-01-05          40
4     B 2023-01-04          30 2023-01-01          40
5     B 2023-01-04          30 2023-01-03          40
6     B 2023-01-04          30 2023-01-02          30
7     B 2023-01-04          30 2023-01-05          40
8     B 2023-01-01          50 2023-01-01          40
9     B 2023-01-01          50 2023-01-03          40
10    B 2023-01-01          50 2023-01-02          30
11    B 2023-01-01          50 2023-01-05          40


In [ ]:




print(pd.concat([df1,df2]).drop_duplicates(subset='Name', keep=False))