In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
o = np.ones((3,4), dtype = int)
o2 = np.zeros((3,4), dtype = int)
o3 = np.ones((3,4), dtype = int)*3

print(o,o2,o3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [13]:
o = np.full((3,4),9,dtype=int)
print(o)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [16]:
# random full
o = np.full((3,4),np.random.randint(1,101),dtype=int)
print(o)

[[88 88 88 88]
 [88 88 88 88]
 [88 88 88 88]]


In [23]:
#random matrix
rand = np.random.randint(1,101,size=(3,4))
rand

array([[ 7, 97, 68, 45],
       [70, 73, 89, 24],
       [50, 31, 43, 74]])

In [36]:
r = np.random.random((3,4))
print(r,end="\n")

r = 30+(50-30)*np.random.random((3,4))
print(r,"\n","\n",r/100)

[[0.71859177 0.94394079 0.57945655 0.24433069]
 [0.98769125 0.51035667 0.50699713 0.04132679]
 [0.2615727  0.71993283 0.11126792 0.27623051]]
[[34.47462019 40.95037025 42.77117687 49.98443599]
 [38.92490159 49.11707011 36.0471741  47.62097839]
 [42.23330381 32.12328083 32.6827478  46.6776077 ]] 
 
 [[0.3447462  0.4095037  0.42771177 0.49984436]
 [0.38924902 0.4911707  0.36047174 0.47620978]
 [0.42233304 0.32123281 0.32682748 0.46677608]]


In [44]:
ar = np.arange(0,101,5) #(start,end+1,steps)
ar

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
#Equal Spaces between the starting and the end
li = np.linspace(10,100,11)
li

array([ 10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])

In [54]:
# array inspection

print(o.shape) #shape eg.(3,3)
print(o.size)
print(o.ndim)

(3, 4)
12
2


In [57]:
cube = np.zeros((3,3,3))
print(cube)

cube.ndim

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


3