In [41]:
import numpy as np

In [42]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [43]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
o = np.ones((3,4), dtype = int)
o2 = np.zeros((3,4), dtype = int)
o3 = np.ones((3,4), dtype = int)*3

print(o,o2,o3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [45]:
o = np.full((3,4),9,dtype=int)
print(o)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [46]:
# random full
o = np.full((3,4),np.random.randint(1,10),dtype=int)
print(o)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [ ]:
#random matrix
rand = np.random.randint(1,11,size=(3,4))
rand

array([[92, 63, 42, 60],
       [39, 76, 32, 57],
       [51, 53,  9, 79]])

In [48]:
r = np.random.random((3,4))
print(r,end="\n")

r = 30+(50-30)*np.random.random((3,4))
print(r,"\n","\n",r/100)

[[0.4075951  0.61176313 0.1690675  0.98965503]
 [0.05531469 0.90419321 0.73099028 0.90472201]
 [0.26139374 0.5764257  0.51741299 0.74858993]]
[[43.82834789 30.20577237 45.5188317  34.34779842]
 [33.56968521 47.97548243 38.67939649 43.87799825]
 [41.23430774 31.44470806 31.79505889 36.30191099]] 
 
 [[0.43828348 0.30205772 0.45518832 0.34347798]
 [0.33569685 0.47975482 0.38679396 0.43877998]
 [0.41234308 0.31444708 0.31795059 0.36301911]]


In [49]:
ar = np.arange(0,101,5) #(start,end+1,steps)
ar

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [50]:
#Equal Spaces between the starting and the end
li = np.linspace(10,100,11)
li

array([ 10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])

In [51]:
# array inspection

print(o.shape) #shape eg.(3,3)
print(o.size)
print(o.ndim)

(3, 4)
12
2


In [52]:
cube = np.zeros((3,3,3),dtype=int)
print(cube)

print(cube.ndim)
print(cube.dtype)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
3
int64


In [53]:
#Modify Shape
o.shape = (1,12)
print(o)

[[4 4 4 4 4 4 4 4 4 4 4 4]]


In [54]:

o = o.reshape(12,1)
print(o)

[[4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]]


In [55]:
#Math Funcs

print("Exponents of an array", np.exp(o))

Exponents of an array [[54.59815003]
 [54.59815003]
 [54.59815003]
 [54.59815003]
 [54.59815003]
 [54.59815003]
 [54.59815003]
 [54.59815003]
 [54.59815003]
 [54.59815003]
 [54.59815003]
 [54.59815003]]
